name: 'Install & build SvelteKit'
description: 'Install SvelteKit dependencies and build the application'
runs:
  using: 'composite'
  steps:
    - name: Install SvelteKit dependencies
      working-directory: ./sveltekit
      run: npm ci
      shell: bash

    - name: Install Prisma's dependencies
      working-directory: ./sveltekit
      run: npx prisma generate && npx prisma migrate dev
      env:
        DATABASE_URL: "file:./Canutin.temp.vault"
        # HACK: need to set the `DATABASE_URL` environment variable because the
        # implementation `sveltekit/src/routes/devTools.json/+server.ts` needs it
        # during the build process, not only it needs the dbURL but also needs a
        # valid vault file, so we also need to run `npx prisma migrate dev` as well.
        # REF: https://github.com/fmaclen/canutin-desktop/issues/205
      shell: bash

    - name: Generate SvelteKit build
      working-directory: ./sveltekit
      run: npm run build:sveltekit
      env:
        DATABASE_URL: "file:./Canutin.temp.vault"
        APP_VERSION: ${{ env.APP_VERSION }}
      shell: bash

    - name: Update package.json's with app version
      run: npm run package:release
      env:
        APP_VERSION: ${{ env.APP_VERSION }}
      shell: bash
