name: Build & release

on:
  pull_request:
    branches: [main, master]
  # push:
  #   branches: [main, master]

jobs:
  tag:
    name: Tag commit
    runs-on: ubuntu-latest
    outputs:
      # new_release_git_tag: ${{ steps.tag_version.outputs.new_release_git_tag }}
      new_release_git_tag: v1.14.3

    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: ${{ needs.tag.outputs.new_release_git_tag != '' }}
    needs: tag
    strategy:
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest] # AFAIK macos-13 is the lastest one on x86

    name: Release (${{ matrix.os }})
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install Electron dependencies
        run: npm ci

      - name: Install SvelteKit dependencies
        working-directory: ./sveltekit
        run: npm ci

      # HACK: need to set the `DATABASE_URL` environment variable because the
      # implementation `sveltekit/src/routes/devTools.json/+server.ts` needs it
      # during the build process, not only it needs the dbURL but also needs a
      # valid vault file, so we also need to run `npx prisma migrate dev` as well.
      # REF: https://github.com/fmaclen/canutin-desktop/issues/205
      - name: Install Prisma's dependencies
        working-directory: ./sveltekit
        run: npx prisma generate && npx prisma migrate dev
        env:
          DATABASE_URL: "file:./Canutin.temp.vault"

      - name: "Generate Electron & Sveltekit builds"
        run: npm run build:all
        env:
          DATABASE_URL: "file:./Canutin.temp.vault"
          APP_VERSION: ${{ needs.tag.outputs.new_release_git_tag }}

      - name: Update package.json's with app version
        run: npm run package:release
        env:
          APP_VERSION: ${{ needs.tag.outputs.new_release_git_tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Push the Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags:
            - ghcr.io/${{ github.actor }}/canutin:latest
            - ghcr.io/${{ github.actor }}/canutin:${{ needs.tag.outputs.new_release_git_tag }}
          platforms: linux/amd64, linux/arm64

      # - name: Build & release Electron app
      #   uses: coparse-inc/action-electron-builder@v1.0.0
      #   with:
      #     github_token: ${{ secrets.github_token }}
      #     build_script_name: "package:electron"
      #     release: true
