name: Build & release

on:
  push:
    branches: [main, master]

jobs:
  tag:
    name: Tag commit
    runs-on: ubuntu-latest
    outputs:
      new_release_git_tag: ${{ steps.tag_version.outputs.new_release_git_tag }}

    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: ${{ needs.tag.outputs.new_release_git_tag != '' }}
    needs: tag
    strategy:
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest] # AFAIK macos-13 is the lastest one on x86

    name: Release (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install Electron dependencies
        run: npm ci

      - name: Install SvelteKit dependencies
        working-directory: ./sveltekit
        run: npm ci

      # HACK: need to set the `DATABASE_URL` environment variable because the
      # implementation `sveltekit/src/routes/devTools.json/+server.ts` needs it
      # during the build process, not only it needs the dbURL but also needs a
      # valid vault file, so we also need to run `npx prisma migrate dev` as well.
      # REF: https://github.com/fmaclen/canutin-desktop/issues/205
      - name: Install Prisma's dependencies
        working-directory: ./sveltekit
        run: npx prisma generate && npx prisma migrate dev
        env:
          DATABASE_URL: "file:./Canutin.temp.vault"

      - name: "Generate Electron & Sveltekit builds"
        run: npm run build:all
        env:
          DATABASE_URL: "file:./Canutin.temp.vault"
          APP_VERSION: ${{ needs.tag.outputs.new_release_git_tag }}

      - name: Update package.json's with app version
        run: npm run package:release
        env:
          APP_VERSION: ${{ needs.tag.outputs.new_release_git_tag }}

      - name: Build & release Electron app
        uses: coparse-inc/action-electron-builder@v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          build_script_name: "package:electron"
          release: true

      - name: Collect all files needed for server release
        # Only create a release for the server when action runs in Ubuntu.
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: npm run package:server
        env:
          APP_VERSION: ${{ needs.tag.outputs.new_release_git_tag }}

      - name: Release server package
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.tag.outputs.new_release_git_tag }}
          files: ./dist/canutin-server_*.tar.gz
