name: SvelteKit Integration Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Current working dir
        working-directory: ./sveltekit
        run: echo "$PWD"
      - name: Install dependencies
        working-directory: ./sveltekit
        run: npm ci
      - name: Install Prisma's dependencies
        working-directory: ./sveltekit
        run: npx prisma generate
      - name: Install Playwright Browsers
        working-directory: ./sveltekit
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./sveltekit
        run: npm test
