name: Test

on:
  pull_request:

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Download PocketBase
        run: |
          wget https://github.com/pocketbase/pocketbase/releases/download/v0.21.3/pocketbase_0.21.3_linux_amd64.zip
          unzip pocketbase_0.21.3_linux_amd64.zip -d pocketbase
          chmod +x pocketbase/pocketbase

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
